### ISSUE TITLE
[Feature request] Better README description & Ctrl+P access does not hide files

### ISSUE THREAD

**Issue by Kristinita** [nicholastay/Sublime-StreamerMode#1]
### Request

It would be nice if you add more description of Usage, examples and screenshots/screencasts.
### Justification

I do not quite understand how your plugin works. It is possible that other users also encounter difficulties in understanding how the StreamMode works.
### Extended behavior

> Open your Preferences (User) and add glob patterns to the hide list

May you write in `README.MD` examples of patterns?

> access to those files will be hidden

What must I do, to see how files are hidden?
### Not helped for me

For example, I don't want, that my file `E:\SashaSublime\README.md` was opened. Part of my `User/Preferences.sublime-settings` file:

``` json
"streamer_mode_enabled": true,
"streamer_mode_hide_files":
[
    "E:/SashaSublime/README.md"
],
```

<kbd>Ctrl+P</kbd> → I print `README.MD` → I select `E:\SashaSublime\README.md` in `Goto Anything...` panel → file `E:\SashaSublime\README.md` was opened for me.

I try `E:\\SashaSublime\\README.md` in settings, but its too not worked for me.

Thanks.

**Comment by nicholastay** [comment]
Thanks for your input. I'll try to go thru each thing you talked about and will attempt to outline what I'll try to do.

**Justification**: "access to those files will be hidden" - it's meant to do that but something below you used I overlooked. I may make a short demo video later once I figure how to resolve this "bug".

**Extended Behavior**: See below.

**Not helped for me**: Your glob patterns are probably correct, it's probably the way you access it with Ctrl+P which I overlooked. If you click the file on the side pane where the project it opened, you should see that access to the file is indeed hidden and you can override this by selecting the option in the command palette. I will try to fix this issue but I am still pretty new to the Sublime API so it may take a while.

**Comment by nicholastay** [comment]
Should be fixed by 8b1b9c6 and e435648 -- sorry it took so long I actually had it done but realized I hadn't pushed it lol

**Comment by Kristinita** [comment]
@nicholastay , may you show in README.MD correct step-by-step example? I have read README.MD several times, but I can not understand, how plugin work.

Thanks.

**Comment by nicholastay** [comment]
@Kristinita If you follow the usage section, it should outline how to use it. I can quickly run through it here: first you open the command palette with Cmd+Shift+P, then you run Streamer Mode: Toggle. That should enable the plugin and also generate the preference keys in your user preferences. (`streamer_mode_hide_files`). You should then edit that array with an array of globs (eg `config.*`) and those globs will be checked every time a file is opened and if they match, the file will be blocked from view (streamer mode). To open the file anyway, you open the command palette again, and run Streamer Mode: Override.

Hopefully that makes a bit more sense, sorry if the readme file is a bit tedious.

**Comment by Kristinita** [comment]
@nicholastay, please, to see my request. **Examples and screenshots/screencasts**.

---

## 1. Stats

+ 0 real examples of usage,
+ 0 screenshots/screencasts,
+ Only [**18 downloads**](https://packagecontrol.io/packages/Streamer%20Mode).

Users don't understand, what Streamer Mode do and no download it. 

**We don't see expected behavior**, what should happen. It is very important.

---

## 2. Example

What I do wrong?

![Streamer](http://i.imgur.com/UZiOEqT.gif)

Also, I try manually add in my `User\Preferences.sublime-settings` file lines

```json
"streamer_mode_enabled": true,
"streamer_mode_hide_files":
[
    "E:/SashaSublime/README.md"
],
```

But I don't see effect.

---

## 3. Questions

> You should then edit that array with an array of globs (eg config.*) and those

I don't understand, what I need to edit :crying_cat_face:.

> Open your Preferences (User) and add glob patterns to the hide list - access to those files will be hidden while streamer mode is active.

Glob patterns format?

---

I'm sorry if my words hurt you, but I think, that developer should not make it harder for users to use the software. And you will have many more users of your packages.

Thanks.

**Comment by nicholastay** [comment]
Made a quick screencast with some spare time I have now -- been really busy with school

https://streamable.com/6jkwe

Also, regarding globs, you could have just googled it ~ https://en.wikipedia.org/wiki/Glob_(programming)
